# Generated by Django 5.2.8 on 2025-11-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='introduction',
            name='seo_description',
            field=models.TextField(blank=True, help_text='توضیحات برای موتورهای جستجو', null=True, verbose_name='توضیحات SEO'),
        ),
        migrations.AddField(
            model_name='introduction',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='کلمات کلیدی با کاما جدا شوند', max_length=500, null=True, verbose_name='کلمات کلیدی SEO'),
        ),
        migrations.AddField(
            model_name='introduction',
            name='seo_title',
            field=models.CharField(blank=True, help_text='اگر خالی باشد از عنوان استفاده می\u200cشود', max_length=200, null=True, verbose_name='عنوان SEO'),
        ),
    ]
